### ISSUE TITLE
RFC: Rename `fastrace::full_name!()` to `fastrace::func_path!()`

### ISSUE THREAD

**Issue by andylokandy** [fastracelabs/fastrace#10]
fastrace has three macros for conveniently acquiring the current span name: `func_name`, `full_path`, and `file_location`. Among these three, `full_path` seems ambiguous. Other motivation is [anyhow](https://docs.rs/anyerror/latest/anyerror/index.html), who also provides two macros `func_name` and `func_path`.

Do you think this change is a good idea? @zhongzc @breezewish @Xuanwo @tisonkun @MrCroxx

**Comment by Xuanwo** [comment]
+1.

I think it's a good idea to rename it to `func_name`. 

Maybe we also deprecate `full_path` first to make users easier to migrate?
